"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# CURRENTLY THE SAME SECRET AMONG INSTANCES --- MIGHT BE GOOD TO PUT IT TO ENVIRONMENT VARIABLE
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'y8epAuZMwFMxEsat1Bkh75ZmkBYcyxq34zbL9YvFAtjrJ433Q1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
if ("debugMode" in os.environ.keys()) and ((os.environ['debugMode'] == '1') or (os.environ['debugMode'] == 1)):
    DEBUG = True 

ALLOWED_HOSTS = os.environ["internalURLs"].split(',') + ["127.0.0.1", "backend.cityflows.imec-apt.be"]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap3',
    'app',
    'corsheaders',
    'oauth2_provider',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'cf',
        'USER': 'cf',
        'PASSWORD': os.environ['dbPass'],
        'HOST': os.environ['dbHost'],
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'CET'
USE_I18N = True
USE_L10N = True
USE_TZ = True

STATIC_URL = '/static/'
#STATIC_ROOT = '/app/app/static/'

import os
SITE_ROOT = os.path.dirname(os.path.realpath(__file__))
STATICFILES_DIRS = (
  '/app/app/static/',
)

LOGIN_REDIRECT_URL = '/'

if 'CORSWhiteListed' in os.environ:
    CORS_ORIGIN_WHITELIST = (os.environ['CORSWhiteListed'],'https://cityflows-api.anyways.eu','http://127.0.0.1','http://172.21.0.77', 'http://172.21.0.77:3737', 'https://cfback.salnikov.be', 'https://backend.cityflows.imec-apt.be', 'https://demo-backend.cityflows.imec-apt.be')
else:
    CORS_ORIGIN_WHITELIST = ('http://127.0.0.1','http://172.21.0.77', 'http://172.21.0.77:3737', 'https://cfback.salnikov.be', 'https://backend.cityflows.imec-apt.be', 'https://demo-backend.cityflows.imec-apt.be')
CORS_ORIGIN_ALLOW = True
CORS_ORIGIN_ALLOW_ALL = True

DATA_UPLOAD_MAX_MEMORY_SIZE = 1024*1024*1024
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

CSRF_TRUSTED_ORIGINS = ['https://gent-backend.cityflows.imec-apt.be', 'https://demo-backend.cityflows.imec-apt.be', 'https://backend.cityflows.imec-apt.be', 'https://cfback.salnikov.be','https://cityflows-api.anyways.eu']